### ISSUE TITLE
ImportError: No module named management.commands.updatecatalog

### ISSUE THREAD

**Issue by baigonvert** [garethbjohnson/gutendex#1]
Hi,
I tried to follow the installation guide and after this command:

`./manage.py updatecatalog`

I end up with this error:

> Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/LocalPath/Python/gutendex/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/LocalPath/Python/gutendex/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/LocalPath/Python/gutendex/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/LocalPath/Python/gutendex/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management.commands.updatecatalog

I'm totally noob to Django and Python, what did I do wrong ?
Thanks...

**Comment by garethbjohnson** [comment]
@baigonvert Hello, I'm really sorry to reply so late.

I recently had a similar problem, because I didn't have the requirements installed in that environment. Thus, I suggest you make sure you have Django and the other requirements installed. You can do this by following Step 3 of the [Installation Guide](https://github.com/garethbjohnson/gutendex/wiki/Installation-Guide).

Please let me know if this helps. Sorry again for being so late to reply! 😅

**Comment by garethbjohnson** [comment]
@baigonvert Aha! I see the problem now. I ran across the same problem today: you're using Python 2 instead of Python 3.

Make sure you have Python 3.5+ installed, and create your virtual environment with `virtualenv -p python3 venv` in Step 3 of the Installation Guide.

Sorry, I should have handled this common use case in the guide. I'll update it now.
